# fly.toml app configuration file generated for maple-charge-worlds on 2023-07-23T12:51:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maple-charge-worlds"
primary_region = "dfw"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
