name: lint

on:
  push:
    branches: [main, v3]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: lint:${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        script: [tsc, eslint, knip]
      fail-fast: false
    name: lint:${{ matrix.script }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run setup
      - run: pnpm run lint:${{ matrix.script }}
